// <auto-generated />
using System;
using FastApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASPFastApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240521165439_a")]
    partial class a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ASPFastApi.Models.Entities.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<string>("ArticleDescription")
                        .HasColumnType("text");

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("Visibility")
                        .HasColumnType("boolean");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "eo te ructqecgesoeu n gdapu",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 2,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "liueu aroeivir le ei uaailper",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 3,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "scieqisuxoiE erE  d iuenn rnef",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 4,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "r osameiesnuuet cl elcsa  edto",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 5,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "niustaco lusebiimmcmsbe qc cpu",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 6,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "aleil eere idrne llueint lr  v",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 7,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "aasqnanemism notaasdqdsuq",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 8,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "uo n  fetueal taeopis",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 9,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "s i cco og don tbeoib",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 10,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "epeoe oilen",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 11,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = " nrfot Ernit baneEq maa  ul i ",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 12,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = " tepisat oene d  st",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 13,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "tdciltple li reuai  dui r aulq",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 14,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "oitiml u ontadmcciitu",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 15,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "ce oivopsiuiUatlnm",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 16,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "iv atusltauttnu  ",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 17,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "de r pifeohrid ula",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 18,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "e em  bsltroiidtsr ltd to dnoa",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 19,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "eanE tsd  aentm simxso",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 20,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "o alrotlauvgte cetral    rufDs",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 21,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "raie u   tpiutip  t",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 22,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "mciueqm aobionel a",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 23,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = " mte ilarugiuuapv lm stirtcir",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 24,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "mtnnic tsiqsds muttterUiectv n",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 25,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "r leonu t",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 26,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = " lv i eearnotnu qo  l",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 27,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "ltttentxe utpul nend",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 28,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "ptstaa  ",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 29,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "mlsepo epedsned ti udotmm",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 30,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "dtu rvoeDn",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 31,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "aeo eoo aluqous ao   ap  sio i",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 32,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "daleae moanm ensd",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 33,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = " npc tludrpummosxuta  m aneulo",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 34,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = " is nntnarisiillt ",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 35,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "q cr oatsiantoaolmanubslunisuc",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 36,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "eerent  eoeaeu utts uo  rpe ",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 37,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "icat loubascte  nobdeiseuisono",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 38,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "xs ueuteaidaetlti u l r sm t u",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 39,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "teu ilvuurloiu le uitl hrpendr",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 40,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "srivuirt oDtsr",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 41,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "uuniui dtegamiourinllvmDuelrlr",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 42,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "uvt eido rloim arnievstl   ant",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 43,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "s m uilonniteutomnrqmsip nalil",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 44,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = " eeni unieoirn aecnstncuactene",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 45,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "tmlmiaeut aiaa isioUr oe tseme",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 46,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "iibtluibfcpe",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 47,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "irv timidtedmti on r da",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 48,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "qctmuaaomsmslolumilra",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 49,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "me i clo Usidtiste",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 50,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "auutsumcon  cusutn op sndfftmc",
                            CategoryId = 10,
                            Visibility = true
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo",
                            CategoryName = "muuutiuefdoienbtcrptr dolmsuuEecpsqu"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            CategoryName = "rai  i"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            CategoryName = " pencdert ui o n oe o"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            CategoryName = "x  iieei n icoi ssiscUimc"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            CategoryName = "gerDoetllhl trea rei"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            CategoryName = " diftlo eldindt n  atptdinldplo cio aeuttirpbp"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo c",
                            CategoryName = "etlnu ui    imt"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea co",
                            CategoryName = "maoiueqas a uqueibccci c tib aolrd ncman tem"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            CategoryName = "ils unec tdmodcpeimoilil emoarc cd dueadL"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla ",
                            CategoryName = "itct uco il b"
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CommentId");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            ArticleId = 36,
                            Content = "sctiuxfasceinao  mdtlao Enntacl p  enelitf stnti qes ueiilr pluda   udpcupepcidicldstslEqoqmicldunpceo  cmnai occsouitn entssupo anoimpuon m e  o lanelcbnto i"
                        },
                        new
                        {
                            CommentId = 2,
                            ArticleId = 36,
                            Content = "enretlhne aiuurpiliius nt rrsna rrfl uvl ur oa puaaatpltilie utrermdrtnsnrl o rshirutl plptnaal  uorr  ic  i fvr haapaeeutie  lrercuprun"
                        },
                        new
                        {
                            CommentId = 3,
                            ArticleId = 44,
                            Content = " i mrropoios de aaloi sltoi eir  s"
                        },
                        new
                        {
                            CommentId = 4,
                            ArticleId = 45,
                            Content = "ilefip EpicbstmidErtepcrt set ctieet cioorcia  cttibe cfr aolcepsdidcnace dnoasunodidso u  a  ec dnaoiu rot iutns i i cmExtd rmpnc accsa imusnoc paaec "
                        },
                        new
                        {
                            CommentId = 5,
                            ArticleId = 15,
                            Content = "er eduesr Litscaq tol  cotsntptiituo "
                        },
                        new
                        {
                            CommentId = 6,
                            ArticleId = 3,
                            Content = "ooe ep dmnraitlrdrdolce siqmpridoo mge ioq tagneidigpldaereudemmme"
                        },
                        new
                        {
                            CommentId = 7,
                            ArticleId = 2,
                            Content = " nrni uotEefd nmcueei iim nssufbuEiEf etc ssp d  un oq a d tpeiannts dano "
                        },
                        new
                        {
                            CommentId = 8,
                            ArticleId = 10,
                            Content = " rru   oileip bl deootenenil tle oco  uo mnunbi ndo   iam eu mputd e pnmar idsaltate daoiltau a irm  neotnin sLa Lasdsiemmciolprtm"
                        },
                        new
                        {
                            CommentId = 9,
                            ArticleId = 11,
                            Content = "nuuaruaapaulanibeuctuoiom runedt tte il tt n cnu istsniinalimcprlndiuimn tat pci r npcraleeiic n nfosiepn  iamfetlmln  ioleonbcttecanuadcinallci u aoln eesi"
                        },
                        new
                        {
                            CommentId = 10,
                            ArticleId = 47,
                            Content = "ip  s etulbp spd amobedu susbareco tidd t nuib a"
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Title = "ot al a"
                        },
                        new
                        {
                            TagId = 2,
                            Title = "dtTddet e"
                        },
                        new
                        {
                            TagId = 3,
                            Title = "sse bWsts "
                        },
                        new
                        {
                            TagId = 4,
                            Title = "aW o daWollb"
                        },
                        new
                        {
                            TagId = 5,
                            Title = "bdsrbTsb sla WW"
                        },
                        new
                        {
                            TagId = 6,
                            Title = "ela allbr eeb"
                        },
                        new
                        {
                            TagId = 7,
                            Title = "laao s"
                        },
                        new
                        {
                            TagId = 8,
                            Title = "dsota a blaabta"
                        },
                        new
                        {
                            TagId = 9,
                            Title = " eTlsbaeWTbasabtd"
                        },
                        new
                        {
                            TagId = 10,
                            Title = "la   batl"
                        },
                        new
                        {
                            TagId = 11,
                            Title = "bTelbTa"
                        },
                        new
                        {
                            TagId = 12,
                            Title = "WTtl addar bblbtera"
                        },
                        new
                        {
                            TagId = 13,
                            Title = "sTWade"
                        },
                        new
                        {
                            TagId = 14,
                            Title = "e abeldal alaWllbe"
                        },
                        new
                        {
                            TagId = 15,
                            Title = "lr ldbd lelWTer "
                        },
                        new
                        {
                            TagId = 16,
                            Title = "bWd badsoTls "
                        },
                        new
                        {
                            TagId = 17,
                            Title = "bWaTt eW   rd "
                        },
                        new
                        {
                            TagId = 18,
                            Title = "t aeal Wa"
                        },
                        new
                        {
                            TagId = 19,
                            Title = "oesbdll rWse"
                        },
                        new
                        {
                            TagId = 20,
                            Title = "W WlbW"
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTag", (string)null);

                    b.HasData(
                        new
                        {
                            ArticleId = 13,
                            TagId = 19
                        },
                        new
                        {
                            ArticleId = 36,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 21,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 6,
                            TagId = 16
                        },
                        new
                        {
                            ArticleId = 37,
                            TagId = 16
                        },
                        new
                        {
                            ArticleId = 38,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 46,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 1,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 48,
                            TagId = 18
                        },
                        new
                        {
                            ArticleId = 10,
                            TagId = 19
                        },
                        new
                        {
                            ArticleId = 31,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 11,
                            TagId = 11
                        },
                        new
                        {
                            ArticleId = 17,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 47,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 22,
                            TagId = 16
                        },
                        new
                        {
                            ArticleId = 14,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 49,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 42,
                            TagId = 11
                        },
                        new
                        {
                            ArticleId = 6,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 38,
                            TagId = 12
                        },
                        new
                        {
                            ArticleId = 41,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 5,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 42,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 13,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 3,
                            TagId = 7
                        },
                        new
                        {
                            ArticleId = 19,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 11,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 7,
                            TagId = 11
                        },
                        new
                        {
                            ArticleId = 6,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 1,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 11,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 39,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 47,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 46,
                            TagId = 9
                        },
                        new
                        {
                            ArticleId = 49,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 36,
                            TagId = 20
                        },
                        new
                        {
                            ArticleId = 21,
                            TagId = 7
                        },
                        new
                        {
                            ArticleId = 28,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 12,
                            TagId = 12
                        },
                        new
                        {
                            ArticleId = 10,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 36,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 49,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 34,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 3,
                            TagId = 11
                        },
                        new
                        {
                            ArticleId = 46,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 38,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 41,
                            TagId = 11
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Article", b =>
                {
                    b.HasOne("ASPFastApi.Models.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Comment", b =>
                {
                    b.HasOne("ASPFastApi.Models.Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("ASPFastApi.Models.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASPFastApi.Models.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
