// <auto-generated />
using System;
using FastApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASPFastApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240606214311_initnew")]
    partial class initnew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ASPFastApi.Models.Entities.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<string>("ArticleDescription")
                        .HasColumnType("text");

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("Visibility")
                        .HasColumnType("boolean");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "stocif o n rpt  dfutisimi e ae",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 2,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "d nbreiauromcug ng ndnm tmdt e",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 3,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "iercuDcpirunrr opueeiuapunlul ",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 4,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "nrumrreimcmteeea e rbqntubrsao",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 5,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "frsnl  dseauuea suuu",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 6,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "iurou uacn e   ae a iimae mnto",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 7,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "mrteimus  lelcussionutqc llecl",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 8,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "im aunes  ",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 9,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "aa   u npe   nituoeot  tamiadf",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 10,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "lmlctm ito",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 11,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "el dt",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 12,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "r rrmrefpisrr",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 13,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "unx  etoe usuo",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 14,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "uegLccee",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 15,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "prrellrru nea  t oidm",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 16,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "tat tLdn toam tis inLel ",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 17,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "r cueau tdcof o dil ncei cnsna",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 18,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = " ot sicli ou atero mtcnrvtxxpe",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 19,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "aoii ra ae isop  ev",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 20,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = " re unevcsouead oeelree eeno l",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 21,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = " eeripieimtgeigit a  i iiiaui ",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 22,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = " utmlp",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 23,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "unc tien tol uomeeitm",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 24,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "dnf vriei odepelueeeps puorir ",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 25,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "appoe n dqen",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 26,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "trdsru rtul alstl  uirnd",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 27,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = " diudtitmaoiresatnmrtrt i",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 28,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "upttfp sDiiuedeoDslnod aue",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 29,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "ueuio uee dfnnnauurliepea itf",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 30,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "tia lasoecsobq cnoarut noniono",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 31,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "mumontsio stt",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 32,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "s lomaliecnptsno  mi",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 33,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "laorc dtn ioeuieodair  U e enl",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 34,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "d xsxa",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 35,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "tecapdncldtiui",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 36,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "eho sde erm rrlaev lnue r otit",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 37,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "aagesai  dasncrehirulisd",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 38,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = " lduculmetimpnn   dt",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 39,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "u t U m ucoaqdsud ",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 40,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "noiintlmotl ",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 41,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "ni sdnnmotfnccmluntttqlrn",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 42,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "ocel niaiqla xnunteinqd",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 43,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "oor mE btrrt",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 44,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "diulidnos uutuhpott ",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 45,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = " lltiadr dur",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 46,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "aieu um uaaoso i nul",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 47,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = " i te rl tianno ntdocmcsiolmmr",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 48,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "lmaeeuiidugrorul ts lareuiaamn",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 49,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "a iu dlooiatnfmormpacaEcneactn",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 50,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "t ioorsso t l cait L sediiodlu",
                            CategoryId = 10,
                            Visibility = true
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            CategoryName = "ou id tcdstu atesmoo ao"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            CategoryName = "eausdert"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            CategoryName = "uru roedo cux suaso nienu io txnitoa sdaiUt"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla ",
                            CategoryName = "iureusatdleD rrnr ispnotlualurap uiruee e tsein"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            CategoryName = "taport ooll o  l a h"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            CategoryName = "eioeruu nx raop eoix  anurm  atpqsl"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            CategoryName = " ednuiedl ic iue aun ri  tmne"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla ",
                            CategoryName = "laa  vemsitnusuobi   ottomdu iict"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            CategoryName = "slrtl inlrm esusccnsnimpu oeii"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ",
                            CategoryName = "tuo o ad tnaaa o  rdasreplla euelolse uneiutd"
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CommentId");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            ArticleId = 38,
                            Content = "ocrouue idqe nitxmm t q ms  sauqsmmunnd tmtvmtis eotn   iana dinuns d nuuucunrt"
                        },
                        new
                        {
                            CommentId = 2,
                            ArticleId = 9,
                            Content = " nUtldorbianqcuemtitq qt ri s ea biUtUm oiec quixeibxae td imtamt xt uax entviaircac   id scn   nm iice iii   a mdxn  iqnpoUmcmieait a"
                        },
                        new
                        {
                            CommentId = 3,
                            ArticleId = 8,
                            Content = "luan tgltriil esn  inadtpd manim tqnuegoi Ln"
                        },
                        new
                        {
                            CommentId = 4,
                            ArticleId = 18,
                            Content = "o ttaerieeel ettisuguaeei ucop"
                        },
                        new
                        {
                            CommentId = 5,
                            ArticleId = 23,
                            Content = "r uieeiupdt eacesdsuoinlmoiuttttsdmiidopdepnLnaiouenmidroabiut  oelegt   taetgs om tseee no toe m soeel s em atLetuimeusg  ss ridu"
                        },
                        new
                        {
                            CommentId = 6,
                            ArticleId = 26,
                            Content = "ls i  u nioits ammaas aci rumn msiqlx qiorii caxi ttuincmbcm qocdaaaavosebiaqano"
                        },
                        new
                        {
                            CommentId = 7,
                            ArticleId = 48,
                            Content = "o emiuaptavn cesq c p lo ait   lbs a n vos  ieibaticsuutiioeieru umaa mmuro ism on nn mo r xrecodqd xtalstn isltia a i o ucxtntqrUd"
                        },
                        new
                        {
                            CommentId = 8,
                            ArticleId = 12,
                            Content = "eeerecesroaolaetlihp  l t ule  geena ialelasrel dt i  ls iuouur e r eutlg rt ieletrvpuam atrlprnfes ostrdoghdolea"
                        },
                        new
                        {
                            CommentId = 9,
                            ArticleId = 15,
                            Content = "sd lxua aimiaqdu  einue ataoeniiidnec sinx"
                        },
                        new
                        {
                            CommentId = 10,
                            ArticleId = 40,
                            Content = "utemoiqt lbmiomsumencsi a dedoiacunmmu   mtrcoatb ndm tteuu  olo q n sria io iteliancei i"
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TagId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Title = "lTbbladslWbdlb"
                        },
                        new
                        {
                            TagId = 2,
                            Title = "rd ldTs db"
                        },
                        new
                        {
                            TagId = 3,
                            Title = "atasdlbbe"
                        },
                        new
                        {
                            TagId = 4,
                            Title = "dralbro"
                        },
                        new
                        {
                            TagId = 5,
                            Title = "rloatlellaWslalddT"
                        },
                        new
                        {
                            TagId = 6,
                            Title = "lTa so bbe"
                        },
                        new
                        {
                            TagId = 7,
                            Title = "ol lseb"
                        },
                        new
                        {
                            TagId = 8,
                            Title = "tTdt "
                        },
                        new
                        {
                            TagId = 9,
                            Title = "tbastTs"
                        },
                        new
                        {
                            TagId = 10,
                            Title = "bebosWW lbelrrTlbr"
                        },
                        new
                        {
                            TagId = 11,
                            Title = "lrrostl ld l lWbTdr"
                        },
                        new
                        {
                            TagId = 12,
                            Title = "dldlrr"
                        },
                        new
                        {
                            TagId = 13,
                            Title = "otdbstlbesebeW"
                        },
                        new
                        {
                            TagId = 14,
                            Title = "btbdbodbetal"
                        },
                        new
                        {
                            TagId = 15,
                            Title = "aaleal srsoWlllTll"
                        },
                        new
                        {
                            TagId = 16,
                            Title = "teT e eoabololale"
                        },
                        new
                        {
                            TagId = 17,
                            Title = "lWseWrl"
                        },
                        new
                        {
                            TagId = 18,
                            Title = "TeabTWedlsoteses sa"
                        },
                        new
                        {
                            TagId = 19,
                            Title = "lbaWtdatltTerleb"
                        },
                        new
                        {
                            TagId = 20,
                            Title = "lTtbtroWdsrllWl"
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTag", (string)null);

                    b.HasData(
                        new
                        {
                            ArticleId = 42,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 5,
                            TagId = 12
                        },
                        new
                        {
                            ArticleId = 1,
                            TagId = 19
                        },
                        new
                        {
                            ArticleId = 22,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 9,
                            TagId = 1
                        },
                        new
                        {
                            ArticleId = 12,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 41,
                            TagId = 20
                        },
                        new
                        {
                            ArticleId = 42,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 12,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 3,
                            TagId = 9
                        },
                        new
                        {
                            ArticleId = 50,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 47,
                            TagId = 9
                        },
                        new
                        {
                            ArticleId = 5,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 42,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 38,
                            TagId = 1
                        },
                        new
                        {
                            ArticleId = 31,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 2,
                            TagId = 12
                        },
                        new
                        {
                            ArticleId = 14,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 47,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 12,
                            TagId = 18
                        },
                        new
                        {
                            ArticleId = 8,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 36,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 47,
                            TagId = 12
                        },
                        new
                        {
                            ArticleId = 20,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 27,
                            TagId = 12
                        },
                        new
                        {
                            ArticleId = 28,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 28,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 31,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 36,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 30,
                            TagId = 20
                        },
                        new
                        {
                            ArticleId = 12,
                            TagId = 9
                        },
                        new
                        {
                            ArticleId = 3,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 43,
                            TagId = 16
                        },
                        new
                        {
                            ArticleId = 27,
                            TagId = 11
                        },
                        new
                        {
                            ArticleId = 41,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 14,
                            TagId = 7
                        },
                        new
                        {
                            ArticleId = 7,
                            TagId = 18
                        },
                        new
                        {
                            ArticleId = 30,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 5,
                            TagId = 20
                        },
                        new
                        {
                            ArticleId = 29,
                            TagId = 16
                        },
                        new
                        {
                            ArticleId = 23,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 11,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 1,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 32,
                            TagId = 20
                        },
                        new
                        {
                            ArticleId = 32,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 31,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 7,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 2,
                            TagId = 11
                        },
                        new
                        {
                            ArticleId = 47,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 10,
                            TagId = 5
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Article", b =>
                {
                    b.HasOne("ASPFastApi.Models.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Comment", b =>
                {
                    b.HasOne("ASPFastApi.Models.Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("ASPFastApi.Models.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASPFastApi.Models.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
