// <auto-generated />
using System;
using FastApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASPFastApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240407165816_initpostgres")]
    partial class initpostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTag", (string)null);

                    b.HasData(
                        new
                        {
                            ArticleId = 13,
                            TagId = 11
                        },
                        new
                        {
                            ArticleId = 41,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 34,
                            TagId = 7
                        },
                        new
                        {
                            ArticleId = 32,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 20,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 35,
                            TagId = 1
                        },
                        new
                        {
                            ArticleId = 42,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 29,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 13,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 33,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 25,
                            TagId = 11
                        },
                        new
                        {
                            ArticleId = 2,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 28,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 45,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 42,
                            TagId = 11
                        },
                        new
                        {
                            ArticleId = 25,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 26,
                            TagId = 16
                        },
                        new
                        {
                            ArticleId = 14,
                            TagId = 20
                        },
                        new
                        {
                            ArticleId = 6,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 8,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 40,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 21,
                            TagId = 9
                        },
                        new
                        {
                            ArticleId = 45,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 37,
                            TagId = 19
                        },
                        new
                        {
                            ArticleId = 27,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 27,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 36,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 45,
                            TagId = 19
                        },
                        new
                        {
                            ArticleId = 9,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 12,
                            TagId = 12
                        },
                        new
                        {
                            ArticleId = 46,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 47,
                            TagId = 20
                        },
                        new
                        {
                            ArticleId = 50,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 33,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 37,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 39,
                            TagId = 18
                        },
                        new
                        {
                            ArticleId = 22,
                            TagId = 1
                        },
                        new
                        {
                            ArticleId = 44,
                            TagId = 12
                        },
                        new
                        {
                            ArticleId = 8,
                            TagId = 18
                        },
                        new
                        {
                            ArticleId = 34,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 21,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 24,
                            TagId = 18
                        },
                        new
                        {
                            ArticleId = 29,
                            TagId = 19
                        },
                        new
                        {
                            ArticleId = 25,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 19,
                            TagId = 9
                        },
                        new
                        {
                            ArticleId = 50,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 14,
                            TagId = 1
                        },
                        new
                        {
                            ArticleId = 18,
                            TagId = 13
                        });
                });

            modelBuilder.Entity("FastApi.Entity.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<string>("ArticleDescription")
                        .HasColumnType("text");

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("Visibility")
                        .HasColumnType("boolean");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "toaldetatoq mevoumqcsc  e iraq",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 2,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "rlpeunl eaaDigphuu",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 3,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = " uutsm sioiimmsaiso ouictaeqsi",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 4,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = " ati aito",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 5,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "inavi i anxu",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 6,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "natel agliilon",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 7,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "xu ctarustri",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 8,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "nf u ifi ed atoe a tsembl",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 9,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "eide  pldtduas lsrul teseo one",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 10,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "al mednu  nq mcoteia  aomiio r",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 11,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "   nn lru lou ltttvn",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 12,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = " edp  rm mtn rssomsitoaarcn",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 13,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "qneuqqa otnUoivimdesuis illt",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 14,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "rerr  udnnvt  e r l  tlivutp a",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 15,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "oo a oaimdnstt dsnlct refnlmcl",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 16,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "nlmiat",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 17,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "arcen iciipmxi  b",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 18,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "din ndl eaea lo",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 19,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = " nnepritiruu mu mi naieodniutr",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 20,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "eevtiidsmalatt xdb o lxda",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 21,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "iuid ite",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 22,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "meceiil nio ico",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 23,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "u ilrrn dra",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 24,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = " umbsmadardnUsrcl",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 25,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "lfsp noirio t a n t opcsnde no",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 26,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "rsreervtilou u llr erupun",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 27,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = " xisoxcmeppruE auoapaclicfin",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 28,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "drtimsdnototidts udeiooruooidd",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 29,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "amq uiecusdtbxUia mqooq urlroi",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 30,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "inqoaiaicai ibeuqrn  ovac elne",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 31,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "natcctx  n  iueolt tnb noblcnp",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 32,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "s smueaimadngurgce uin iqesuee",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 33,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "a neutde rnfEi",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 34,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "omtup aonip duiua",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 35,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "mi mnerame c c",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 36,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "i dei i pet  ltdctmo eaom ttei",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 37,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "ianaqop",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 38,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "dlteraeau rrttiur sDe lDee",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 39,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "ueomt ",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 40,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "tgtceiu",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 41,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "olsusnad omisrs",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 42,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "oe tp ti",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 43,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "d un pp",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 44,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = " s lnut",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 45,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "i e ooa autaougi   lvolravve ",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 46,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = " aoiam itrti ri",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 47,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = " eataonrlcnim cttpl eitpintaec",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 48,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "uutaiooiedbunpctaae n tt",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 49,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "pcr l pd a",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 50,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "tintro ds ei soeaeuirc nuex nt",
                            CategoryId = 10,
                            Visibility = true
                        });
                });

            modelBuilder.Entity("FastApi.Entity.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labo",
                            CategoryName = "o imomc epcueduet oneuo rie ot snaloaroeea"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id ",
                            CategoryName = "i  c em   opta olot octsepa"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            CategoryName = "sir vaa onioudrr ttn e v pfvlelella"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla ",
                            CategoryName = "ioar euttn  deiDl lesanpev  duiratiemco i "
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            CategoryName = "reddarst rdq dls  dui eu"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            CategoryName = "tou ftstqbsleec"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ",
                            CategoryName = "v gsr re   eh trreDrlerurtuuprheaeemiiuilDrldtnum"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla ",
                            CategoryName = "op cmscqEi  e "
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            CategoryName = " pr oecd tinloicc cn tu   ioufnf"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pari",
                            CategoryName = "an looiivuocaincire ei xUisrstinmnerxca c dsa"
                        });
                });

            modelBuilder.Entity("FastApi.Entity.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CommentId");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            ArticleId = 26,
                            Content = "dam uruapu  aurttebuofnanadtblrl  qpeianuuE rcnmieptudo f rsotcnolonit umreodndndoqcl t nao ecrtuatsimxrcoid pofai"
                        },
                        new
                        {
                            CommentId = 2,
                            ArticleId = 31,
                            Content = " tofnetplnfnciaeceelou ttouasm oracn lfu on cnmcinsre iuiiulcquu rixEtmramtaoiendftptedaafsllla cccataras uniuoox lu cfcostciic cictntittcrotoe Enmtfbst"
                        },
                        new
                        {
                            CommentId = 3,
                            ArticleId = 45,
                            Content = " etodi mnmurop bir o ridl xn  uxm uo"
                        },
                        new
                        {
                            CommentId = 4,
                            ArticleId = 26,
                            Content = "iu ia mtpesaoavapesit ie Dirutueeddguole"
                        },
                        new
                        {
                            CommentId = 5,
                            ArticleId = 4,
                            Content = "iupsu n op  t m   uuclaiixttf rt"
                        },
                        new
                        {
                            CommentId = 6,
                            ArticleId = 46,
                            Content = "tis uuatl aourn arelirduingn"
                        },
                        new
                        {
                            CommentId = 7,
                            ArticleId = 4,
                            Content = "cle u pdaen   ctEonionsiEcl e boitacari  maat cutntinecnstifdmc dpcn  fiuiaidacpa  bdalutidlanqitaq Ea ndcttuautectE utemo uotsElu ntt iuii ut ap"
                        },
                        new
                        {
                            CommentId = 8,
                            ArticleId = 17,
                            Content = " titol  rcttltnsu eepetotisianeruiertsm sdame ooae"
                        },
                        new
                        {
                            CommentId = 9,
                            ArticleId = 50,
                            Content = "rstrne  diiieeu  dtr astuhirtvutea  ealaeoet l"
                        },
                        new
                        {
                            CommentId = 10,
                            ArticleId = 11,
                            Content = "rdoca  tcerat ua oenaleixtsur qiclssinu  tqod uiosn tmnt bntidla sii b qimruq qcb atmaietaoxoirteleo aemisa u niua irneasq cuneco sitiacaiib"
                        });
                });

            modelBuilder.Entity("FastApi.Entity.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Title = "olTsls a TT"
                        },
                        new
                        {
                            TagId = 2,
                            Title = " rbaa WalWrTbaa"
                        },
                        new
                        {
                            TagId = 3,
                            Title = "W eosdW tbl t "
                        },
                        new
                        {
                            TagId = 4,
                            Title = "WTdllalras a"
                        },
                        new
                        {
                            TagId = 5,
                            Title = "abatatWdWddesa T "
                        },
                        new
                        {
                            TagId = 6,
                            Title = "abbabbbTralla"
                        },
                        new
                        {
                            TagId = 7,
                            Title = "abeaodlWstla blWWrs"
                        },
                        new
                        {
                            TagId = 8,
                            Title = "To b WT asabdaWT"
                        },
                        new
                        {
                            TagId = 9,
                            Title = "WaetlWreas"
                        },
                        new
                        {
                            TagId = 10,
                            Title = "aWs  alabbblW a"
                        },
                        new
                        {
                            TagId = 11,
                            Title = "Wo asdb"
                        },
                        new
                        {
                            TagId = 12,
                            Title = "ala l sal"
                        },
                        new
                        {
                            TagId = 13,
                            Title = "oTbdrW ab "
                        },
                        new
                        {
                            TagId = 14,
                            Title = "loda  aa  a odTb"
                        },
                        new
                        {
                            TagId = 15,
                            Title = "slTbrlrdsabbosdabl"
                        },
                        new
                        {
                            TagId = 16,
                            Title = " bsarTaa"
                        },
                        new
                        {
                            TagId = 17,
                            Title = " da l abtd l"
                        },
                        new
                        {
                            TagId = 18,
                            Title = "t o ssllbl la"
                        },
                        new
                        {
                            TagId = 19,
                            Title = "l o drb W  odeWa l"
                        },
                        new
                        {
                            TagId = 20,
                            Title = "borlo  lerW"
                        });
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("FastApi.Entity.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastApi.Entity.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FastApi.Entity.Article", b =>
                {
                    b.HasOne("FastApi.Entity.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FastApi.Entity.Comment", b =>
                {
                    b.HasOne("FastApi.Entity.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("FastApi.Entity.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("FastApi.Entity.Category", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
