// <auto-generated />
using System;
using FastApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASPFastApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ASPFastApi.Models.Entities.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<string>("ArticleDescription")
                        .HasColumnType("text");

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("Visibility")
                        .HasColumnType("boolean");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "oiigapiepislvil fun",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 2,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "d rudt lmdcgrL ciaeaddtsnue rd",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 3,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = " t tsEa ",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 4,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "xtsbl euoitiuettd  i ",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 5,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "ono a eeirm",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 6,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "lonii  ",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 7,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "eed nt rciae t eirrrlr reeun",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 8,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "ueei n  actdamstotbbEr",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 9,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "q ti eo exlr nsvd osloci duna ",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 10,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "n ss red",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 11,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "ruatsu  a  nqsq  x  tmqm i mri",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 12,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "meoiLraetdictar  uiaqc tlio  i",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 13,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "cre srdLdraddedcmabi uitmocgua",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 14,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = " oq dece rgeastms gi p uspaurd",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 15,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "uustenlasislm f fl brd ",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 16,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "a oeldtccau ulaxinoacbrnaa u u",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 17,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "tentuicm srcd tft  or ",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 18,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = " q eqmocx xod dtuudxsoasueat",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 19,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "ii  uti",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 20,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "uouveh deulhi fr nuelld nei",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 21,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "eu  el peopo r fru",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 22,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "dammc ",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 23,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "drashlear  eaiueer r e lret fl",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 24,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "toardaiannueloleruui tioD d",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 25,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "sii u qli nai titUsaaersu amos",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 26,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "turipttocn p",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 27,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "mniiudt om l cttiieeu e dold q",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 28,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "teonitox roittciqc cxniqaioino",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 29,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "lirtioom",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 30,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "l ma    oe   lp elci pootd pu ",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 31,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "tp sopaisedi  ac re  s",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 32,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = " visi  ltlsmcti eraut q i il",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 33,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "afuiox u  eait oa   oxtn",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 34,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "nb e   r  cileasune enlaboidic",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 35,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "siioasui  u miqmaem   l im a x",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 36,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "s nu xndue  tnaiiifns xuoe  uu",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 37,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "tocrxrlridanu",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 38,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "r i euoenbcn d  ittL ",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 39,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "vereliDde l ripeslotretmr",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 40,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "rttote renudmamcnrn  mp",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 41,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "uae eooe",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 42,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "aeudnr",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 43,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "Dlllrdcnnhrogfaric ",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 44,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "c qaniqso",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 45,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "m  udsor  odesmeasa diontmuptr",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 46,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "i es i meuroete",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 47,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "duu  lr  ntoo o o etoftr",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 48,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "ao u t inq",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 49,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "txiis xnbac",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 50,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "aeeoe litl iieunrtuntrt eanrt ",
                            CategoryId = 10,
                            Visibility = true
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            CategoryName = " arcr meamilco",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            CategoryName = "rotot  qi o m rosuieppps tudtid musianeeo",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            CategoryName = "ne  og e roipsc dm ir ttardiomu cesriarettm",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            CategoryName = "lne muUu tuvaotvmtuv",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit a",
                            CategoryName = "n umi i r  dqlsca eeds oapcslp inorusmtto mtitot",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            CategoryName = "snoUauci exucri",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labo",
                            CategoryName = "m qruolncetuuittct oatnsltg",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo c",
                            CategoryName = "esiadaus ptnuoioimr ",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea co",
                            CategoryName = "nel c t ii mtouutneuUim  eui pemqcm",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo c",
                            CategoryName = "fdn   natt asacnpt",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CommentId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            ArticleId = 44,
                            Content = "o is uu po accu osra  udim io uenrma  cmsndmmt rv i tr o eiea s maur itx  oi miitnainaiu ondoomaoi oa r"
                        },
                        new
                        {
                            CommentId = 2,
                            ArticleId = 15,
                            Content = "  acqiupqmbmc eabbot  n U  ciui u radmal ut axedtae dc inqs p ianai annilqossmmdsoar U  nscasxneonio  cuamiieUirodurntbinu xissmiaq   osai  catecatinm d"
                        },
                        new
                        {
                            CommentId = 3,
                            ArticleId = 42,
                            Content = " inu oudgdpltat doeqiraegd  cniqieeqaalduu iLrociu aroursbmutrl t is tnieelLaslleu nm e onditdueii  s nelooo eists "
                        },
                        new
                        {
                            CommentId = 4,
                            ArticleId = 29,
                            Content = "xi ta  a t naa tu mie  ttcoutaurnuaiioionuet oamm oqemd rimiiob qitsmn odaqn o ibicsd iiearitide scnaax Ux tl"
                        },
                        new
                        {
                            CommentId = 5,
                            ArticleId = 45,
                            Content = "einneonibsndi  iainiu utetmnunssetas lttnpunuicuitcltosuqctisn nE ad r "
                        },
                        new
                        {
                            CommentId = 6,
                            ArticleId = 43,
                            Content = "tmcouaaooemsomedaa adm omUs dttUraenoeac oincseo  cmut i ommn mmUmeonu c  em mnac eUnqu"
                        },
                        new
                        {
                            CommentId = 7,
                            ArticleId = 30,
                            Content = "m lrn avvienlopru lopueuhrccliva vnud ut hmilpverevndurua gosea ovauu rr"
                        },
                        new
                        {
                            CommentId = 8,
                            ArticleId = 23,
                            Content = "riaend ot vosg nuualdsatauriteddds eirhilnld impoDirnstuthiepdadugto iuuce ae  oaritea rluaralaluareumpcvieuoatd ru afgmuiee soslrsa eri  tuviu  "
                        },
                        new
                        {
                            CommentId = 9,
                            ArticleId = 35,
                            Content = "goitno eaatonltgaeotbemc mdrc"
                        },
                        new
                        {
                            CommentId = 10,
                            ArticleId = 30,
                            Content = "iedutetslt  np sipletoo dealrrvua ue siarttllp ieltceireerveotm fitriuolulvreae aagvveraal o uono uriprruree ieneuiuune u"
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TagId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Title = "lbtess"
                        },
                        new
                        {
                            TagId = 2,
                            Title = "b boloblolbW oltT"
                        },
                        new
                        {
                            TagId = 3,
                            Title = "tatbWolr eTr"
                        },
                        new
                        {
                            TagId = 4,
                            Title = "t Tel"
                        },
                        new
                        {
                            TagId = 5,
                            Title = "esboebrbTsrebdlr"
                        },
                        new
                        {
                            TagId = 6,
                            Title = "ooobWab"
                        },
                        new
                        {
                            TagId = 7,
                            Title = "btbadltarWlWlrd"
                        },
                        new
                        {
                            TagId = 8,
                            Title = "dWrotar"
                        },
                        new
                        {
                            TagId = 9,
                            Title = "b oobel"
                        },
                        new
                        {
                            TagId = 10,
                            Title = "lsbWardTtTal"
                        },
                        new
                        {
                            TagId = 11,
                            Title = "etb rWTtbabrolr"
                        },
                        new
                        {
                            TagId = 12,
                            Title = "le Wlt a"
                        },
                        new
                        {
                            TagId = 13,
                            Title = "ldbleblWottWs lW o"
                        },
                        new
                        {
                            TagId = 14,
                            Title = "lbredoT"
                        },
                        new
                        {
                            TagId = 15,
                            Title = "dTTbtls"
                        },
                        new
                        {
                            TagId = 16,
                            Title = "blbb dalWstlat s"
                        },
                        new
                        {
                            TagId = 17,
                            Title = "oralsob"
                        },
                        new
                        {
                            TagId = 18,
                            Title = "btlar"
                        },
                        new
                        {
                            TagId = 19,
                            Title = "aWTebaebbtrTol"
                        },
                        new
                        {
                            TagId = 20,
                            Title = "osrtoltdsaoror os"
                        });
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "test",
                            Username = "test"
                        });
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTag", (string)null);

                    b.HasData(
                        new
                        {
                            ArticleId = 9,
                            TagId = 18
                        },
                        new
                        {
                            ArticleId = 17,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 18,
                            TagId = 7
                        },
                        new
                        {
                            ArticleId = 48,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 10,
                            TagId = 12
                        },
                        new
                        {
                            ArticleId = 46,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 49,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 37,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 18,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 15,
                            TagId = 19
                        },
                        new
                        {
                            ArticleId = 3,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 40,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 27,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 49,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 38,
                            TagId = 20
                        },
                        new
                        {
                            ArticleId = 37,
                            TagId = 11
                        },
                        new
                        {
                            ArticleId = 32,
                            TagId = 18
                        },
                        new
                        {
                            ArticleId = 40,
                            TagId = 19
                        },
                        new
                        {
                            ArticleId = 31,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 32,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 20,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 4,
                            TagId = 7
                        },
                        new
                        {
                            ArticleId = 9,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 11,
                            TagId = 16
                        },
                        new
                        {
                            ArticleId = 27,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 22,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 36,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 44,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 36,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 48,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 48,
                            TagId = 18
                        },
                        new
                        {
                            ArticleId = 41,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 8,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 39,
                            TagId = 7
                        },
                        new
                        {
                            ArticleId = 40,
                            TagId = 20
                        },
                        new
                        {
                            ArticleId = 24,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 46,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 35,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 37,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 19,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 17,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 9,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 17,
                            TagId = 9
                        },
                        new
                        {
                            ArticleId = 2,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 16,
                            TagId = 19
                        },
                        new
                        {
                            ArticleId = 29,
                            TagId = 7
                        },
                        new
                        {
                            ArticleId = 20,
                            TagId = 12
                        },
                        new
                        {
                            ArticleId = 6,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 32,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 16,
                            TagId = 13
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Article", b =>
                {
                    b.HasOne("ASPFastApi.Models.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASPFastApi.Models.Entities.User", null)
                        .WithMany("Articles")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Comment", b =>
                {
                    b.HasOne("ASPFastApi.Models.Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId");

                    b.HasOne("ASPFastApi.Models.Entities.User", null)
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("ASPFastApi.Models.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASPFastApi.Models.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("ASPFastApi.Models.Entities.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
