// <auto-generated />
using System;
using FastApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASPFastApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTag", (string)null);

                    b.HasData(
                        new
                        {
                            ArticleId = 18,
                            TagId = 1
                        },
                        new
                        {
                            ArticleId = 26,
                            TagId = 7
                        },
                        new
                        {
                            ArticleId = 28,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 18,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 16,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 49,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 6,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 24,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 22,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 39,
                            TagId = 16
                        },
                        new
                        {
                            ArticleId = 38,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 40,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 9,
                            TagId = 16
                        },
                        new
                        {
                            ArticleId = 31,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 9,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 41,
                            TagId = 16
                        },
                        new
                        {
                            ArticleId = 37,
                            TagId = 16
                        },
                        new
                        {
                            ArticleId = 11,
                            TagId = 16
                        },
                        new
                        {
                            ArticleId = 13,
                            TagId = 12
                        },
                        new
                        {
                            ArticleId = 3,
                            TagId = 11
                        },
                        new
                        {
                            ArticleId = 27,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 28,
                            TagId = 6
                        },
                        new
                        {
                            ArticleId = 21,
                            TagId = 20
                        },
                        new
                        {
                            ArticleId = 16,
                            TagId = 20
                        },
                        new
                        {
                            ArticleId = 27,
                            TagId = 20
                        },
                        new
                        {
                            ArticleId = 34,
                            TagId = 19
                        },
                        new
                        {
                            ArticleId = 23,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 20,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 49,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 18,
                            TagId = 18
                        },
                        new
                        {
                            ArticleId = 40,
                            TagId = 11
                        },
                        new
                        {
                            ArticleId = 36,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 46,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 20,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 28,
                            TagId = 12
                        },
                        new
                        {
                            ArticleId = 42,
                            TagId = 1
                        },
                        new
                        {
                            ArticleId = 49,
                            TagId = 18
                        },
                        new
                        {
                            ArticleId = 1,
                            TagId = 19
                        },
                        new
                        {
                            ArticleId = 30,
                            TagId = 15
                        },
                        new
                        {
                            ArticleId = 32,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 18,
                            TagId = 13
                        },
                        new
                        {
                            ArticleId = 42,
                            TagId = 8
                        },
                        new
                        {
                            ArticleId = 21,
                            TagId = 17
                        },
                        new
                        {
                            ArticleId = 48,
                            TagId = 20
                        },
                        new
                        {
                            ArticleId = 7,
                            TagId = 7
                        },
                        new
                        {
                            ArticleId = 38,
                            TagId = 10
                        },
                        new
                        {
                            ArticleId = 13,
                            TagId = 14
                        },
                        new
                        {
                            ArticleId = 29,
                            TagId = 18
                        });
                });

            modelBuilder.Entity("FastApi.Entity.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<string>("ArticleDescription")
                        .HasColumnType("text");

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("Visibility")
                        .HasColumnType("boolean");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "tqonneaiieu bp",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 2,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "a tru iudriiiip ",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 3,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = " ndn  mUox boltd xlmbuqnemuena",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 4,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "ier ta",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 5,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "d upntge aoeea rtc nu anli eiu",
                            CategoryId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 6,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "Letidmeoiiiai io",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 7,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "rrusxeusirrde",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 8,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "i misiuere ru erinni audeleulf",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 9,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = " l ctixnetxi l",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 10,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "aprmeehea erup",
                            CategoryId = 2,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 11,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "aopilo uib ac isot sodedpoemip",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 12,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "bmisnta p  q ina tiue p",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 13,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "soaoetet cioxcstlrrbtsso tne f",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 14,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "ciiix ta",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 15,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "uinirae  ltee maua irilidddlnn",
                            CategoryId = 3,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 16,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "eeliipeurfeafrveu u erstr nodu",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 17,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "xttla Ulvqqt t Un uioots uddim",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 18,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "imodrdi qiau aeitldotsgoddt ld",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 19,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "dsl dc   lleu s  nsnqseb",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 20,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "msodntntnli biiiiurimc  fdtpin",
                            CategoryId = 4,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 21,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "acrcc ioreddd im icdd die r o ",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 22,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "d lttesci tdtelnom",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 23,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "exclso",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 24,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "raopio iului sdseutlrtpiltsaeu",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 25,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "trld g t",
                            CategoryId = 5,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 26,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "ssn euetosmmeoiina i xtiea",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 27,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "dadu lpadsiliit tmna",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 28,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "Llqsr dreuolid odaao ",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 29,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "elie ft  harioe  lcs vaooler",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 30,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = " oo i m mb mmdnostuoie nib ",
                            CategoryId = 6,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 31,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "tvitr lsu eudnuid ldrpnersmaap",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 32,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "lfu le eir t   oeeri lcanatadi",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 33,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "mcasmo ins o iasnnin  uisac ta",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 34,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "ioqrcqitn ecacuuc  xsedoi ",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 35,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "oieol c iosuourearD rial  esef",
                            CategoryId = 7,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 36,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = " aeiiteumitqa saqeda  s",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 37,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "a edr  rialimgon ",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 38,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "cstpor  ennccauoe loiepo dsu",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 39,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "ec cuucpu inmm smadmlai a alq",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 40,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            ArticleName = "curarrrlriuiaetitcredaeanennln",
                            CategoryId = 8,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 41,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "ntru ep m   e nit aurl eD eout",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 42,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "rt lsma ",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 43,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "iul lsernrtpa ef hinlo  anaina",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 44,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            ArticleName = "piqen n ui mt qnsua i i",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 45,
                            ArticleDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "t  ie mguti  sr ed  dleupaiiin",
                            CategoryId = 9,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 46,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "u Eisudoa i otc smpirauo ",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 47,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = " nontao",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 48,
                            ArticleDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "as  gtp oetgui epr o",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 49,
                            ArticleDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            ArticleName = "oderocsLtaaoq",
                            CategoryId = 10,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 50,
                            ArticleDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum",
                            ArticleName = "aoiat  enaotteurnenut",
                            CategoryId = 10,
                            Visibility = true
                        });
                });

            modelBuilder.Entity("FastApi.Entity.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                            CategoryName = "eiasct mtedlib "
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea co",
                            CategoryName = "omstiilo nool pemasl nd u"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla ",
                            CategoryName = "acnqo"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim",
                            CategoryName = " e    a "
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nul",
                            CategoryName = " m nEtldltunsinudannxinml arciittlefosi tci oomti"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryDescription = "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea co",
                            CategoryName = " teeutrciuele qpeue  oios aes  u   m"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut ",
                            CategoryName = "ddtpasiam"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia des",
                            CategoryName = "tt lerdollciol oluaslnuuleu"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryDescription = "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
                            CategoryName = "e r erteicdpupaa lodcltst rcdpltmo bd"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryDescription = "Lorem ipsum dolor sit amet  consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            CategoryName = "c pr io lti ne et eemuanc "
                        });
                });

            modelBuilder.Entity("FastApi.Entity.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CommentId");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            ArticleId = 50,
                            Content = "o uqv ne ltllmioan qaicestUd rtpeop ineiiqtvxtiranooaisad c sdestn raoem slbp qm pm  timmai uu aasodieooud osemnd man"
                        },
                        new
                        {
                            CommentId = 2,
                            ArticleId = 26,
                            Content = "mnaaem qqobaictmoctdnuaio ea memrsi qsxnnrtuss bmuimmuacmc nmdmcdmstebaedciola itn   ciidsaoacuoisct ootovi roeieo qeieoimli ssi"
                        },
                        new
                        {
                            CommentId = 3,
                            ArticleId = 12,
                            Content = "tolinoiccditatUrtssammiaamuaa  i xcldao dccxdnuepaq s  sq ssemieexmsuoiavxemnvai omqo loiuiiniuou"
                        },
                        new
                        {
                            CommentId = 4,
                            ArticleId = 6,
                            Content = "tlteneut rqt  atdiamianuqu ili sainn m oi mti teonqoiir uiomolU ooi  uneimmiqau rrc  o  litqio tdbtuotqounasosa"
                        },
                        new
                        {
                            CommentId = 5,
                            ArticleId = 20,
                            Content = "eeiidqeceitplgobnudm  tol puoanse i titorioieamiilu  isalaio"
                        },
                        new
                        {
                            CommentId = 6,
                            ArticleId = 5,
                            Content = "unt asn iuteoteei ruilr iepsipr ies "
                        },
                        new
                        {
                            CommentId = 7,
                            ArticleId = 21,
                            Content = "ittmrta  nlcliicatla"
                        },
                        new
                        {
                            CommentId = 8,
                            ArticleId = 13,
                            Content = "puanfnldtluctaaipuno eis ieui  ttt riomoui uErirplsoupieitbtaanrcosonltocaftnuu "
                        },
                        new
                        {
                            CommentId = 9,
                            ArticleId = 46,
                            Content = "ruaultutl aradlrim   l slanrirriuesniigtiilpdpeocaeuul"
                        },
                        new
                        {
                            CommentId = 10,
                            ArticleId = 2,
                            Content = "druahoaldanauutaenvufmoltner  sl eavauetesnirluei asli lipuntniroall errtuioiahloi dnidouiov nelru  ruol ltilrepdeuointfuteuagusv uerphtlrutlin ora"
                        });
                });

            modelBuilder.Entity("FastApi.Entity.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Title = "baalellalWbltT a"
                        },
                        new
                        {
                            TagId = 2,
                            Title = "l bWstblolrae"
                        },
                        new
                        {
                            TagId = 3,
                            Title = "ddd oa"
                        },
                        new
                        {
                            TagId = 4,
                            Title = " elToadtrbaabtoea"
                        },
                        new
                        {
                            TagId = 5,
                            Title = "a eeWsea"
                        },
                        new
                        {
                            TagId = 6,
                            Title = "a bWo"
                        },
                        new
                        {
                            TagId = 7,
                            Title = " eo WlTalb"
                        },
                        new
                        {
                            TagId = 8,
                            Title = "etttdl o"
                        },
                        new
                        {
                            TagId = 9,
                            Title = " r t lrs as"
                        },
                        new
                        {
                            TagId = 10,
                            Title = "be asab bTla   "
                        },
                        new
                        {
                            TagId = 11,
                            Title = "Wte tosaobll"
                        },
                        new
                        {
                            TagId = 12,
                            Title = "serTbdWso TWrabr r"
                        },
                        new
                        {
                            TagId = 13,
                            Title = " oers d albaW  TlsW"
                        },
                        new
                        {
                            TagId = 14,
                            Title = "ltslbeodaab broetr "
                        },
                        new
                        {
                            TagId = 15,
                            Title = "oTaWera d"
                        },
                        new
                        {
                            TagId = 16,
                            Title = "as bsell  detl"
                        },
                        new
                        {
                            TagId = 17,
                            Title = "a dlldaslta"
                        },
                        new
                        {
                            TagId = 18,
                            Title = "sebtoaealter ol Wa"
                        },
                        new
                        {
                            TagId = 19,
                            Title = "earsdoW"
                        },
                        new
                        {
                            TagId = 20,
                            Title = "aadtllrorrbTb lao a"
                        });
                });

            modelBuilder.Entity("FastApi.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("FastApi.Entity.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastApi.Entity.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FastApi.Entity.Article", b =>
                {
                    b.HasOne("FastApi.Entity.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FastApi.Entity.Comment", b =>
                {
                    b.HasOne("FastApi.Entity.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("FastApi.Entity.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("FastApi.Entity.Category", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
